# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mslice\plotting\plot_window\plot_options.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(297, 476)
        self.gridLayout_3 = QtGui.QGridLayout(Dialog)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.label = QtGui.QLabel(Dialog)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout_3.addWidget(self.label, 0, 0, 1, 1)
        self.lneFigureTitle = QtGui.QLineEdit(Dialog)
        self.lneFigureTitle.setObjectName(_fromUtf8("lneFigureTitle"))
        self.gridLayout_3.addWidget(self.lneFigureTitle, 0, 1, 1, 1)
        self.label_3 = QtGui.QLabel(Dialog)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout_3.addWidget(self.label_3, 1, 0, 1, 1)
        self.lneXAxisLabel = QtGui.QLineEdit(Dialog)
        self.lneXAxisLabel.setObjectName(_fromUtf8("lneXAxisLabel"))
        self.gridLayout_3.addWidget(self.lneXAxisLabel, 1, 1, 1, 1)
        self.label_2 = QtGui.QLabel(Dialog)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout_3.addWidget(self.label_2, 2, 0, 1, 1)
        self.lneYAxisLabel = QtGui.QLineEdit(Dialog)
        self.lneYAxisLabel.setObjectName(_fromUtf8("lneYAxisLabel"))
        self.gridLayout_3.addWidget(self.lneYAxisLabel, 2, 1, 1, 1)
        self.buttonBox = QtGui.QDialogButtonBox(Dialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.gridLayout_3.addWidget(self.buttonBox, 8, 0, 1, 2)
        self.chkShowErrorBars = QtGui.QCheckBox(Dialog)
        self.chkShowErrorBars.setObjectName(_fromUtf8("chkShowErrorBars"))
        self.gridLayout_3.addWidget(self.chkShowErrorBars, 7, 0, 1, 2)
        self.groupBox = QtGui.QGroupBox(Dialog)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.verticalLayout = QtGui.QVBoxLayout(self.groupBox)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.chkShowLegends = QtGui.QCheckBox(self.groupBox)
        self.chkShowLegends.setObjectName(_fromUtf8("chkShowLegends"))
        self.verticalLayout.addWidget(self.chkShowLegends)
        self.gridLayout_3.addWidget(self.groupBox, 6, 0, 1, 2)
        self.groupBox_3 = QtGui.QGroupBox(Dialog)
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.gridLayout_2 = QtGui.QGridLayout(self.groupBox_3)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.label_6 = QtGui.QLabel(self.groupBox_3)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout_2.addWidget(self.label_6, 0, 0, 1, 1)
        self.lneYMin = QtGui.QLineEdit(self.groupBox_3)
        self.lneYMin.setObjectName(_fromUtf8("lneYMin"))
        self.gridLayout_2.addWidget(self.lneYMin, 0, 1, 1, 1)
        self.label_7 = QtGui.QLabel(self.groupBox_3)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout_2.addWidget(self.label_7, 1, 0, 1, 1)
        self.lneYMax = QtGui.QLineEdit(self.groupBox_3)
        self.lneYMax.setObjectName(_fromUtf8("lneYMax"))
        self.gridLayout_2.addWidget(self.lneYMax, 1, 1, 1, 1)
        self.chkYLog = QtGui.QCheckBox(self.groupBox_3)
        self.chkYLog.setObjectName(_fromUtf8("chkYLog"))
        self.gridLayout_2.addWidget(self.chkYLog, 2, 0, 1, 1)
        self.gridLayout_3.addWidget(self.groupBox_3, 4, 0, 1, 2)
        self.groupBox_2 = QtGui.QGroupBox(Dialog)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.gridLayout = QtGui.QGridLayout(self.groupBox_2)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label_4 = QtGui.QLabel(self.groupBox_2)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout.addWidget(self.label_4, 0, 0, 1, 1)
        self.lneXMin = QtGui.QLineEdit(self.groupBox_2)
        self.lneXMin.setObjectName(_fromUtf8("lneXMin"))
        self.gridLayout.addWidget(self.lneXMin, 0, 1, 1, 1)
        self.label_5 = QtGui.QLabel(self.groupBox_2)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout.addWidget(self.label_5, 1, 0, 1, 1)
        self.lneXMax = QtGui.QLineEdit(self.groupBox_2)
        self.lneXMax.setObjectName(_fromUtf8("lneXMax"))
        self.gridLayout.addWidget(self.lneXMax, 1, 1, 1, 1)
        self.chkXLog = QtGui.QCheckBox(self.groupBox_2)
        self.chkXLog.setObjectName(_fromUtf8("chkXLog"))
        self.gridLayout.addWidget(self.chkXLog, 2, 0, 1, 1)
        self.gridLayout_3.addWidget(self.groupBox_2, 3, 0, 1, 2)
        self.groupBox_4 = QtGui.QGroupBox(Dialog)
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.gridLayout_4 = QtGui.QGridLayout(self.groupBox_4)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.lblCMin = QtGui.QLabel(self.groupBox_4)
        self.lblCMin.setObjectName(_fromUtf8("lblCMin"))
        self.gridLayout_4.addWidget(self.lblCMin, 0, 0, 1, 1)
        self.lneCMin = QtGui.QLineEdit(self.groupBox_4)
        self.lneCMin.setObjectName(_fromUtf8("lneCMin"))
        self.gridLayout_4.addWidget(self.lneCMin, 0, 1, 1, 1)
        self.lblCMax = QtGui.QLabel(self.groupBox_4)
        self.lblCMax.setObjectName(_fromUtf8("lblCMax"))
        self.gridLayout_4.addWidget(self.lblCMax, 1, 0, 1, 1)
        self.lneCMax = QtGui.QLineEdit(self.groupBox_4)
        self.lneCMax.setObjectName(_fromUtf8("lneCMax"))
        self.gridLayout_4.addWidget(self.lneCMax, 1, 1, 1, 1)
        self.chkLogarithmic = QtGui.QCheckBox(self.groupBox_4)
        self.chkLogarithmic.setObjectName(_fromUtf8("chkLogarithmic"))
        self.gridLayout_4.addWidget(self.chkLogarithmic, 2, 0, 1, 1)
        self.gridLayout_3.addWidget(self.groupBox_4, 5, 0, 1, 2)

        self.retranslateUi(Dialog)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), Dialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(_translate("Dialog", "Plot Options", None))
        self.label.setText(_translate("Dialog", "Figure Title", None))
        self.label_3.setText(_translate("Dialog", "X axis ", None))
        self.label_2.setText(_translate("Dialog", "Y axis", None))
        self.chkShowErrorBars.setText(_translate("Dialog", "Show Error Bars", None))
        self.groupBox.setTitle(_translate("Dialog", "Legends", None))
        self.chkShowLegends.setText(_translate("Dialog", "Show Legends", None))
        self.groupBox_3.setTitle(_translate("Dialog", "Y axis", None))
        self.label_6.setText(_translate("Dialog", "Min", None))
        self.label_7.setText(_translate("Dialog", "Max", None))
        self.chkYLog.setText(_translate("Dialog", "Logarithmic", None))
        self.groupBox_2.setTitle(_translate("Dialog", "X axis", None))
        self.label_4.setText(_translate("Dialog", "Min", None))
        self.label_5.setText(_translate("Dialog", "Max", None))
        self.chkXLog.setText(_translate("Dialog", "Logarithmic", None))
        self.groupBox_4.setTitle(_translate("Dialog", "Colorbar", None))
        self.lblCMin.setText(_translate("Dialog", "Min", None))
        self.lblCMax.setText(_translate("Dialog", "Max", None))
        self.chkLogarithmic.setText(_translate("Dialog", "Logarithmic", None))

